# Generated by Django 4.2.7 on 2023-11-16 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('floors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('enclosure_id', models.AutoField(primary_key=True, serialize=False)),
                ('square_foot', models.PositiveIntegerField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.building')),
            ],
        ),
    ]
